### ISSUE TITLE
vibrate is not a function

### ISSUE THREAD

**Issue by uncomputable** [uncomputable/simfony-webide#47]
The [vibrate method](https://docs.rs/web-sys/latest/web_sys/struct.Navigator.html#method.vibrate_with_pattern) of the navigator seems to be fallible.

```
Uncaught TypeError: getObject(...).vibrate is not a function
    __wbg_vibrate_37aacc0c0e10e86f https://simfony.dev/simplicity-webide-7959bbca3cb43274.js:854
    __wbg_adapter_36 https://simfony.dev/simplicity-webide-7959bbca3cb43274.js:215
    real https://simfony.dev/simplicity-webide-7959bbca3cb43274.js:200
    __wbg_call_89af060b4e1523f2 https://simfony.dev/simplicity-webide-7959bbca3cb43274.js:1041
    handleError https://simfony.dev/simplicity-webide-7959bbca3cb43274.js:248
    __wbg_call_89af060b4e1523f2 https://simfony.dev/simplicity-webide-7959bbca3cb43274.js:1040
    __wbg_adapter_49 https://simfony.dev/simplicity-webide-7959bbca3cb43274.js:227
    real https://simfony.dev/simplicity-webide-7959bbca3cb43274.js:200
```

**Comment by uncomputable** [comment]
This is a potential bug in wasm-bindgen. I have to check again after updating leptos to 0.7, which should also update wams-bindgen.
